### ISSUE TITLE
Which version should one use?

### ISSUE THREAD

**Issue by robertotru** [RepreZen/KaiZen-OpenApi-Parser#210]
Hello.

I need some clarifications about versions. Maven Central reports that latest release is **3.0.1-201808070540**

![image](https://user-images.githubusercontent.com/2987914/44983041-12bb4800-af78-11e8-8d72-9a806e85e644.png)

However, the master branch is on **2.2.0-SNAPSHOT** and I was expecting **3.0.2-SNAPSHOT** or similar.

There is also an example in the [GettingStarted](https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/master/GettingStarted.md) page that uses the method `getPathInParent()` from `Path` class which seems to not exists either in **3.0.1-201808070540** and **2.1.1-201803281732** release.

Am I missing something?

**Comment by andylowry** [comment]
Hi @robertotru. Sorry for the confusion and thanks for pointing it out. I need to be more conscientious about these things, not just code deveopment.

I've just changed the snapshot version to 3.0.2, and I've updated the Getting Started document as well as the README and the API Overview.
