### ISSUE TITLE
Build Errors when trying to load into Eclipse Neon

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenApi-Parser#34]
Tried loading the project into Neon, and I see the following errors:

Description | Resource | Path | Location | Type
------------- | ---------- | ----- | --------- |  ------
The project was not built since its build path is incomplete. Cannot find the class file for com.google.common.base.Predicate. Fix the build path then try building this project | kaizen-openapi-parser | | Unknown | Java Problem
The type com.google.common.base.Predicate cannot be resolved. It is indirectly referenced from required .class files | Resolver.java | /kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/jsonoverlay | line 1 | Java Problem

**Comment by andylowry** [comment]
This was due to a corrupt local mvn cache on Ted's workstation. Fixed by removing existing guava items and then performing a maven update in eclipse.
