### ISSUE TITLE
Test failures in ExamplesTest

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenApi-Parser#47]
Recommendations from [Getting Started Guide](https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/master/GettingStarted.md) to run `mvn package` to build locally don't work anymore because of four test failures in `ExamplesTest`.
* The first failure is invalid YAML in example, see https://github.com/OAI/OpenAPI-Specification/pull/1228
* One case of `model.collections/securitySchemes.apikey.openIdConnectUrl: Required field is missing [openIdConnectUrl]`
* Others are missing schema type:
 `model.collections/schemas.Error.type: Required field is missing [type]`

Because of it, to get a local build we need to skip the tests.

**Comment by andylowry** [comment]
@tfesenko This has been resolved by a combination of #61, #72 and #73. All tests now succeed.
