### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenApi-Parser#67]
Extracted from #48.
Maven artifacts are currently published to Bintray, but using Bintrays sometimes requires extra configuration, e.g. for internal mirrors

**Comment by andylowry** [comment]
Current status: We've been allocated com.reprezen.kaizen group id in oss.sonatype repo. We still need to review our pom files to ensure they meet requirements, and also get clarification on a question regarding code signing. Hoping for this to be in central within the next day or two.l

**Comment by andylowry** [comment]
This is now complete, and `com.reprezen.kaizen:openpi-parser` now lives in maven central: https://repo.maven.apache.org/maven2/com/reprezen/kaizen/openapi-parser/

@slinkydeveloper @maybeec @paolovmr You should now be able to find project artifacts on maven central. Please let us know if you have any problem with that. Thanks!

**Comment by maybeec** [comment]
wow thanks a lot!
